#!/bin/bash

XBPS_DISTDIR="$(xdistdir)" || exit 1

files=()

for f; do
	fp=
	case "$f" in
		srcpkgs/*) fp="${f#srcpkgs/}" ;;
		*/*) fp="$f" ;;
		*) fp="$f/template" ;;
	esac
	fp="$(realpath "$XBPS_DISTDIR/srcpkgs/$fp" 2>/dev/null)" && files+=("$fp") || echo "ERROR: could not find $f" >&2
done

if [ "${#files[@]}" -gt 0 ]; then
    exec $EDITOR "${files[@]}"
fi
