#!/bin/bash
# xrls [-R rsyncurl] pkgname pkgname ...: list files on the mirrors
# rsyncurl should be in the format "rsync://.../current/"

ARGS=""
REPO="rsync://repo-default.voidlinux.org/voidlinux/current/"

if [ "$1" = "-R" ]; then
	if [[ "$2" =~ rsync://.*/current/ ]]; then
		REPO="$2"
	else
		printf '\033[1m=> Specified repository is not an rsync url ending in /current/, ignoring\n\033[m' 1>&2
	fi
	shift 2
fi

for pkg in $@; do
	ARGS+=" --include=*$pkg*"
done

rsync --dry-run \
	--out-format='%n' \
	--recursive \
	--include '*/' \
	$ARGS \
	--exclude='*' \
	$REPO | \
	awk '/(\.xbps(\.sig2?)?|-repodata)$/ { $1=$2=$3=$4=""; print "/current/" substr($0,5); }' | \
	sort -u
